[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bio_digital_defense = "5r6fERX6CtJ8RHzpf5wLtY1SfptV8rk4JEHfu6yh5WZV"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
